version: '3'
services:
  web:
    image: nginx:1.15.6
    ports:
      - '80:80'
    depends_on:
      - app
    volumes:
      - .:/var/www/html
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build: ./docker/php
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: step
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: